### ISSUE TITLE
rvm or rbenv check for ruby

### ISSUE THREAD

**Issue by pamo** [kdabir/dq#8]
Check for both and tally score on whether either exist?
I personally prefer rbenv :grin: 
https://github.com/sstephenson/rbenv

**Comment by kdabir** [comment]
now the commands (name) need to be passed on from cli. Concept of groups was not well thought of... getting rid of that.

**Comment by dexterous** [comment]
IDK, I liked the way groups worked out, esp with the `.dqrc` file.
https://github.com/dexterous/dq/blob/bash-only/dq#L135

**Comment by kdabir** [comment]
@dexterous yes the plan is to have some kind of *rc file to store required command names. It can be current directory or home. And then `has` checks for the commands specified in the rc file.
